### ISSUE TITLE
ng serve Error

### ISSUE THREAD

**Issue by utiq** [EasySolutionsIO/ngx-actioncable#2]
![image](https://user-images.githubusercontent.com/1144196/45968974-43c2f180-bfe7-11e8-97db-d546a2812931.png)

When I execute `ng serve` after stopping the previous instance

Angular CLI: 1.7.4
Node: 7.9.0
OS: darwin x64
Angular: 4.4.7

**Comment by wurmrobert** [comment]
Sorry for the late response?

What version of the lib are you using? The latest one?
I think version `1.1.2` will only work with angular > 6.0.0.

Could you try the lib version `1.0.0`?

**Comment by wurmrobert** [comment]
closed due to inactivity.
