### ISSUE TITLE
Cant use this library. It thows errors on ng serve

### ISSUE THREAD

**Issue by alexcoroza** [EasySolutionsIO/ngx-actioncable#3]
I followed the documentation step by step.
1. installed the library via npm
2. added this code into app.module
    import { NgxActionCableModule, NgxActionCableConfiguration } from 'ngx-actioncable'; (havent put into imports array yet)
3. Ran ng serve

Then it throws errors(in the picturee
![error full](https://user-images.githubusercontent.com/16507120/50199371-6a48bc80-038b-11e9-8265-5ca26b9f199d.png)
)

**Comment by wurmrobert** [comment]
Sorry for that late response.

What Angular, CLI and Node version are you using?

**Comment by wurmrobert** [comment]
Sorry for the late response.

What version of the lib are you using?

**Comment by wurmrobert** [comment]
closed due to inactivity.
